### ISSUE TITLE
Feature request : statut d'unité pour gérer le cas où une unité est dispo, mais pas à sa base

### ISSUE THREAD

**Issue by titixbrest** [adentes-org/preums#2]

**Comment by lcpdn** [comment]
Yep. Ajouté.
Tu peux ajouter autant de statuts que tu veux en modifiant le code ici:
/www/ui/js/gast.res.js

**Comment by sapk** [comment]
L'objectif final aurait été que cette partie (liste des status) soit configurable à partir de l'UI.

**Comment by titixbrest** [comment]
le problème est que le statut "disponible" créé compte comme un véhicule en intervention.

**Comment by lcpdn** [comment]
C'est modifié. Au delà de ce statut particulier, on devrait avoir comme feature de pouvoir ajouter des statuts qui compte ou non comme en intervention.

**Comment by titixbrest** [comment]
C'était l'esprit du ticket en effet

**Comment by lcpdn** [comment]
Ce ticket est fermé, le statut est rajouté. L'ajout d'un statut est dans la liste des features de la v+1
